# -*- coding: utf-8 -*-
"""praktikum5.ddp^

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1coKF6yZo2sGZ1MUjyCdId9SngKPOw5
"""

namaKendaraan = "Beat Ember"
jenisKendaraan = "Motor"
ccKendaraan= 200
warnaKendaraan= "Hitam"
rodaKendaraan= 2

data_kendaraan = [namaKendaraan, jenisKendaraan, ccKendaraan, warnaKendaraan, rodaKendaraan]

print(data_kendaraan)

hargaKendaraan = 5000
tipeKendaraan = "metic"

data_kendaraan.append(hargaKendaraan)
data_kendaraan.append(tipeKendaraan)
print(data_kendaraan)

merkKendaraan = "Honda"
data_kendaraan.insert(2, merkKendaraan)
print(data_kendaraan)





pilihan = input("""
Silahkan pilih menu yang diinginkan
===================================
1. Luas Persegi
2. Luas Lingkaran
3. Luas Segitiga
===================================
Kirimkan hanya angka saja,
jawaban = """)

match pilihan:
  case "1":
    print("anda memilih luas persegi silahkan isi data dibawah")
    sisi = int(input("sisi = "))
    luas = sisi * sisi

    print(f"luas persegi dengan sisi {sisi} adalah {luas}")
    # luas persegi
  case "2":
    #luas lingkaran
    #pi * jarijari**2
    print("anda memilih luas segitiga silahkan isi data dibawah")
    jarijari = int(input("jarijari = "))
    luas_lingkaran = 3.14 * jarijari**2

    print(f"luas lingkaran dengan jarijari {jarijari} adalah {luas_lingkaran}")

  case "3":
    # luas segitiga
    # (alas * tinggi)/2
    print("anda memilih luas segitiga silahkan isi data di bawah")
    alas = int(input("alas = "))
    tinggi = int(input("tinggi = "))
    luas = alas * tinggi /2

    print (f"luas segitiga dengan alas {alas} dan tinggi {tinggi} adalah {luas}")
    # Luas segitiga

  case _:
    print("ya nda tau kok tanya saya si")